services:
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: [ "server", "--console-address", ":9001", "/data" ]
    
    ports:
      - "9000:9000"
      - "9001:9001"
  tf-registry:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
